### ISSUE TITLE
1.1 为什么需要 Rust 编码规范 和 1.2 编码规范基本约定 两个文档缺失

### ISSUE THREAD

**Issue by genedna** [Rust-Coding-Guidelines/rust-coding-guidelines-zh#125]
在 [Github Page](https://rust-coding-guidelines.github.io/rust-coding-guidelines-zh/overview.html)  网站点击以下两个链接的时候，显示 **404** 错误：

```
1.1 为什么需要 Rust 编码规范
1.2 编码规范基本约定 两个文档缺失
```

链接分别是：

- https://rust-coding-guidelines.github.io/safe-guides/overview/why.html
- https://rust-coding-guidelines.github.io/safe-guides/overview/convention.html

**Comment by ZhangHanDong** [comment]
@genedna  没有啊

https://rust-coding-guidelines.github.io/rust-coding-guidelines-zh/overview.html
