### ISSUE TITLE
漏写clippy lint

### ISSUE THREAD

**Issue by surechen** [Rust-Coding-Guidelines/rust-coding-guidelines-zh#126]
G.MOD.05 不要在私有模块中设置其内部类型或函数方法为 pub(crate) 对应 clippy redundant_pub_crate
此处应该是漏写了clippy推荐

**Comment by ZhangHanDong** [comment]
我修正一下

**Comment by ZhangHanDong** [comment]
已加 [https://github.com/Rust-Coding-Guidelines/rust-coding-guidelines-zh/pull/128](https://github.com/Rust-Coding-Guidelines/rust-coding-guidelines-zh/pull/128)
但是这个lint 目前是 nursery 的
