### ISSUE TITLE
编号方式中的ELEMENT母缩写不合理

### ISSUE THREAD

**Issue by tsung-li** [Rust-Coding-Guidelines/rust-coding-guidelines-zh#17]
缩写会导致理解困难

1. RFE ->  引用; 正常看到REF是很困惑的，RUST里面更容易立即的是REF
1. TRA, STV, MTH, OTH 不看中文， 根本无法理解含义， MTH这种更容易理解为MATH这种

**Comment by ZhangHanDong** [comment]
@tsung-li 感谢反馈，确实是个问题，我考虑将缩写修正一下。

**Comment by odd-cat** [comment]
ELEMENT编码中只有IO是两字符的，考虑换成**FIO**?
https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87152270

**Comment by ZhangHanDong** [comment]
@odd-cat 感谢反馈，有道理，可以修改

**Comment by ZhangHanDong** [comment]
已修正。
