### ISSUE TITLE
建议渲染版导航栏的索引详细到二级标题（规范名称）

### ISSUE THREAD

**Issue by wangkirin** [Rust-Coding-Guidelines/rust-coding-guidelines-zh#34]
![image](https://user-images.githubusercontent.com/12807239/141435209-dcaa9711-6f6a-43e6-8e56-07703eae7f4b.png)
如图，现有的渲染版导航栏标题只到章节，读者对每小节的规范规模情况没有直观的概念，建议详细到二级标题，也就是规范名称，便于查阅

**Comment by ZhangHanDong** [comment]
好主意

**Comment by ZhangHanDong** [comment]
@wangkirin 感觉不太好加这个

**Comment by wangkirin** [comment]
> @wangkirin 感觉不太好加这个

我试了一下，mdbook的导航栏只支持导航到某个markdown 文件,  可以以目录形式加到内容头部替代
