### ISSUE TITLE
关于getter/setter命名规范问题

### ISSUE THREAD

**Issue by legenddcr** [Rust-Coding-Guidelines/rust-coding-guidelines-zh#47]
https://rust-coding-guidelines.github.io/rust-coding-guidelines-zh/safe-guides/code_style/naming.html#gnam05-%E7%94%A8%E4%BA%8E%E8%AE%BF%E9%97%AE%E6%88%96%E8%8E%B7%E5%8F%96%E6%95%B0%E6%8D%AE%E7%9A%84-gettersetter-%E7%B1%BB%E6%96%B9%E6%B3%95%E9%80%9A%E5%B8%B8%E4%B8%8D%E8%A6%81%E4%BD%BF%E7%94%A8-get_-%E6%88%96-set_-%E7%AD%89%E5%89%8D%E7%BC%80

在参考这条规则过程中，遇到一个问题：这条规则针对的只是struct的field访问接口还是这个struct的所有访问API？有人理解是针对field的，我理解不应该只针对field。如果说struct的field不需要加get/set，而通过field name + mut命名来解决，那么这样的API实际上暴露了struct的实现，作为使用者，并不关心struct的某个get种类的API `get_foo` 是通过计算实现的还是struct内部真的有一个`foo`字段，破坏了封装。

另外一个相关的问题，如果对于其他非field access类型的API，风格不让用get和set，那么foo()来获取，set value的方法如何命名？

**Comment by ZhangHanDong** [comment]
@legenddcr 感谢反馈，稍后来讨论。

**Comment by ZhangHanDong** [comment]
此条已修正。
