### ISSUE TITLE
P.TYP.Slice.01 【利用切片迭代器来代替手工索引】示例代码有误

### ISSUE THREAD

**Issue by whjpji** [Rust-Coding-Guidelines/rust-coding-guidelines-zh#6]
https://github.com/Rust-Coding-Guidelines/rust-coding-guidelines-zh/blob/e7e9d3be4220e4b6e80d71776cc74d799e28391e/src/safe-guides/coding_practice/data-type/slice.md?plain=1#L24

该行代码示例有两个错误：

1. [`[T]::windows`方法](https://doc.rust-lang.org/std/primitive.slice.html#method.windows)需要一个`size`参数代表窗口大小。
2. 其返回的迭代器的`Item = &'a [T]`不能直接绑定到类型为`[T; 2]`的参数列表`[previous, current]`上。

改正办法是：
```Rust
for [previous, current] in points.array_windows().copied() {
    differences.push(current - previous);
}
```
但目前仅nightly版本支持。

**Comment by Ayawen01** [comment]
现在还是这个例子，不打算改过来吗

**Comment by ZhangHanDong** [comment]
@Ayawen01  打算啊，没有抽出时间而已。或者你有空的话可以帮忙发个PR 。

**Comment by ZhangHanDong** [comment]
@whjpji 感谢反馈，已修正，晚点部署。
