### ISSUE TITLE
请问“尽量不要使用 Unicode 标识符”的缘由？

### ISSUE THREAD

**Issue by nobodxbodon** [Rust-Coding-Guidelines/rust-coding-guidelines-zh#61]
<img width="688" alt="Screen Shot 2022-01-08 at 1 21 06 PM" src="https://user-images.githubusercontent.com/392497/148660378-73309fab-aa29-4fc7-9b91-aeff6b29ae96.png">

试着将例程的标识符用中文命名（对错误码含义不了解仅作直译，如有错谬请指出），效果如下：
<img width="853" alt="Screen Shot 2022-01-08 at 1 41 54 PM" src="https://user-images.githubusercontent.com/392497/148660959-d4958af3-6c0a-4982-bce3-b5eabffa0805.png">

**Comment by ZhangHanDong** [comment]
@nobodxbodon 


1. 你可以可以从示例代码中看到，团队成员可能来自不同国家，这样代码风格会比较乱。
2. 安全原因：https://zhuanlan.zhihu.com/p/428305373
3. 静态检查只识别英文标识符。
4. 习惯问题。大家都习惯英文编程。

如果你的团队使用中文或其他unicode，只要你的团队都同意，那也是可以的。这里给出的只是参考，具体你们团队内部如何约束，就是你们自己决定了。

**Comment by nobodxbodon** [comment]
@ZhangHanDong 


>     1. 你可以可以从示例代码中看到，团队成员可能来自不同国家，这样代码风格会比较乱。

个人了解的情况是，除了国内少数几个头部公司中的少数项目，其他公司的项目绝大多数仅有国内开发者参与？

>     2. 安全原因：https://zhuanlan.zhihu.com/p/428305373

文中使用英文命名标识符同样会有安全问题吧？

>     3. 静态检查只识别英文标识符。

技术上静态检查可以支持中文标识符吧？

>     4. 习惯问题。大家都习惯英文编程。

习惯不意味着今后仍最优吧。从 [此插件使用情况](https://plugins.jetbrains.com/plugin/14838-chinesepinyin-codecompletionhelper/) 看，国内使用中文命名的已不是个别。

> 如果你的团队使用中文或其他unicode，只要你的团队都同意，那也是可以的。这里给出的只是参考，具体你们团队内部如何约束，就是你们自己决定了。

对不少国内开发者，中文命名在 [一些情况下](https://www.zhihu.com/question/437644040/answer/1660325367) 的确可以提高代码可读性，相对于英文命名更“清晰、明了，有明确含义，容易理解”。

在这种情况下，仅不提倡而不给出明显理由的话，作为规范，恐怕给人武断之感？

**Comment by sunli829** [comment]
@ZhangHanDong 赞同，中文编程可以考虑木兰或者易语言。

**Comment by ZhangHanDong** [comment]
@nobodxbodon  我已经说过了，这个规范只是参考，你想用中文也可以，你们团队内部可以指定自己的约束。

请恕不再回复该问题。

**Comment by ZhangHanDong** [comment]
@nobodxbodon  我觉得你要推广中文编程，大可不必来这里推广。

**Comment by nobodxbodon** [comment]
@sunli829 虽然无关本话题，但还是澄清一下，木兰语法并未使用中文，而且原始木兰（风波时的版本）并不支持中文标识符。

Unicode 命名标识符毕竟已被大多常用语言支持，望以开放心态看待越来越多的实践。
