### ISSUE TITLE
github pages的首页overview的org图片路径错误

### ISSUE THREAD

**Issue by odd-cat** [Rust-Coding-Guidelines/rust-coding-guidelines-zh#73]
github pages的首页overview的org图片路径错误：
https://rust-coding-guidelines.github.io/rust-coding-guidelines-zh/
![org](https://user-images.githubusercontent.com/49889967/153114998-fd64fc35-27f3-4204-928a-f0df054bac7c.jpg)

**Comment by ZhangHanDong** [comment]
已修正
