### ISSUE TITLE
原则、规则区别不清楚

### ISSUE THREAD

**Issue by QiangHeisenberg** [Rust-Coding-Guidelines/rust-coding-guidelines-zh#9]
> 标识为P为原则（Principle）。编号方式为P.Element.Number。
> 标识为G为规则（Guideline）。编号方式为G.Element.Number。

按照公司内其他编程语言的规范来说，如果规则意味着编程时必须遵守的约定，那么原则代表什么？建议？还是必须准守的约定？这个区别不是很清楚，可否增加清楚地描述？或者说这两者的定义标准是什么？

**Comment by ZhangHanDong** [comment]
@QiangHeisenberg  

原则，就是编程开发时指导的一个大方向，或是指一类情况，没有那么具体。原则只是一种建议。
规则，是相对原则而言，是更加具体的条目。规则里面有写【建议】还是【必须】遵守。规则一般是可lint检测的。

原则没有办法去检测，所以只能是建议。

**Comment by ZhangHanDong** [comment]
我回头加到说明里
